export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  FILE_CHECKED_OUT = 'FILE_CHECKED_OUT',
  FILE_NOT_CHECKED_OUT = 'FILE_NOT_CHECKED_OUT',
  ODOO_CONNECTION_FAILED = 'ODOO_CONNECTION_FAILED',
  WOOCOMMERCE_CONNECTION_FAILED = 'WOOCOMMERCE_CONNECTION_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
